
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 14 20:50:45 CST 2014
//----------------------------------------------------

package com.zll.main;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RPAREN = 6;
  public static final int error = 1;
  public static final int PLUS = 3;
  public static final int NUMBER = 7;
  public static final int SEMI = 2;
  public static final int LPAREN = 5;
  public static final int TIMES = 4;
  public static final int EOF = 0;
}

